import bogazici from "@/assets/icons/bogazici.png"
import itu from "@/assets/icons/itu.png"
import medx from "@/assets/icons/md2x.png"
import stride from "@/assets/icons/stride.png"
import coderunner from "@/assets/icons/coderunner.png"
import dreamix from "@/assets/icons/dreamix.png"
const details = {
  name: {
    first: "Davyd",
    last: "Yang",
    nickname: "Davyd",
  },
  title: "Senior Software Engineer",
  biography: "Accomplished **Full Stack Developer** with extensive experience in both **frontend** and **backend** technologies, including **React, Next.js,Vue.js, Laravel, Django, Java, .Net, Golang, Ruby, React Native and Flutters**. Known for delivering high-quality web and **mobile applications** that prioritize performance, scalability,and user experience. Dedicated to embracing new challenges and staying ahead of industry trends through continuous learning and innovation",
  education: [
    {
      school: "Boğaziçi University",
      url: "https://bogazici.edu.tr/",
      icon: bogazici,
      iconMin: bogazici,
      location: "Istanbul, Turkey",
      degree: "Master's Degree",
      major: "Computer Science",
      start: "June 2012",
      end: "June 2014",
    },
    {
      school: "Istanbul Technical University",
      url: "https://www.itu.edu.tr/en",
      icon: itu,
      iconMin: itu,
      location: "Istanbul, Turkey",
      degree: "Bachelor's Degree",
      major: "Computer Engineering",
      start: "Aug 2007",
      end: "May 2012",
    },
  ],
  experience: [
    {
      company: "QHCONSULTING.DE",
      url: "https://qhconsulting.de/",
      icon: medx,
      iconMin: medx,
      location: "Runken, Germany",
      contract: "Full-time",
      position: "Senior Software Engineer",
      start: "Aug 2020",
      end: "Present",
      description: [
        "In my tenure at QH Consulting.DE, a leading IT consulting firm, I spearheaded the development of various large-scale project such as e-commerce platforms, designed to transform the digital marketplace.",
        "Leading the architectural design and implementation of the web application using **React** and **Next.js**, focusing on optimizing SEO and enhancing user engagement through server-side rendering. This approach significantly improved the platform's performance, making it highly responsive and search engine friendly.",
        "Orchestrating the development of a cross-platform mobile application with **React Native**, ensuring a uniform and engaging shopping experience across **iOS and Android** devices. My leadership facilitated the incorporation of interactive features such as **live chat** support and **instant purchase notifications**, enhancing customer satisfaction.",
        "Directing the integration of **Vue.js** in frontend development, paired with a robust **Laravel** backend, to create a seamless, scalable e-commerce ecosystem. This setup effectively managed a vast array of products and user interactions, supporting dynamic content updates and secure transactions.",
        "Innovating backend services with **Django**, focusing on crafting efficient **RESTful APIs** and leveraging **GraphQL** for advanced data handling. This enabled sophisticated product search, recommendations, and user personalization features, driving an intuitive and tailored shopping experience.",
        "Managing the deployment of the e-commerce platform on **AWS**, utilizing **Docker** for effective containerization and **microservices** for modular architecture. This strategic approach ensured scalability and resilience, essential for handling **high-volume traffic** and sales events.",
        "Implementing a comprehensive **CI/CD** pipeline with **Git** for version control, fostering a collaborative development environment. My commitment to best practices in code reviews and continuous integration significantly accelerated the delivery cycle, maintaining high code quality and system reliability.",
        "Incorporating **Kafka** and **RabbitMQ** for reliable message brokering between **microservices**, and utilizing **gRPC** for efficient inter-service communication. This was pivotal in supporting **real-time inventory updates, order processing, and analytics**, ensuring a smooth operational flow."
      ],
      skills: [
        "React",
        "Next.js",
        "React Native",
        "Vue.js",
        "Laravel",
        "Django",
        "RESTful APIs",
        "GraphQL",
        "AWS",
        "Docker",
        "Microservices",
        "Kafka",
        "RabbitMQ",
        "gRPC",
        "Git",
        "Jira"
      ],
    },
    {
      company: "STRIDE",
      url: "https://www.stridehealth.com/",
      icon: stride,
      iconMin: stride,
      location: "NU, United States",
      contract: "Contract",
      position: "Full Stack Developer",
      start: "Aug 2017",
      end: "Apr 2020",
      description: [
        "In my most recent role as a Full Stack Developer at a leading technology firm specializing in healthcare solutions, I spearheaded the development of a cutting-edge, patient-centric application designed to improve healthcare outcomes and accessibility. My responsibilities encompassed both the creation and continuous enhancement of the application, utilizing an advanced technology stack that included Angular, React, Vue.js, Laravel, PHP, JavaScript, and DiJava.",
        "Leveraging **Angular**, I developed dynamic and interactive front-end user interfaces, ensuring an intuitive and seamless user experience for patients and healthcare providers alike. My expertise in **Java-based backend** solutions significantly contributed to the application's robust performance and scalability, addressing the critical demands of enterprise-level healthcare environments.",
        "A key project achievement was the integration of **React** and **Vue.js** with **Laravel-powered backends**, which facilitated the creation of a highly responsive and modular application architecture. This approach allowed for rapid development cycles and enhanced maintainability of the codebase. Additionally, I optimized database operations by skillfully utilizing **MySQL** and integrating **Redis** as an efficient caching layer, thereby achieving substantial improvements in data retrieval times and overall application performance.",
        "My role also extended to the establishment and maintenance of **GitLab CI/CD** pipelines, which were instrumental in automating the deployment process. This not only accelerated the delivery of new features and updates but also upheld the highest standards of code quality across the development team. I actively engaged in the **Agile** development process, contributing to sprint planning, daily **stand-ups**, and **retrospectives**, thereby fostering a collaborative and efficient project environment.",
        "I further enhanced the application's reliability and user trust by implementing comprehensive **automated testing strategies**, supporting a **test-driven development (TDD)** approach. My dedication to excellence also involved the design and deployment of scalable and secure **cloud-native** applications on the **Google Cloud Platform (GCP)**, making full use of its managed services and robust infrastructure to ensure high availability and compliance with healthcare regulations.",
      ],
      skills: ["Angular", "Laravel", "PHP", "Typescript", "Java", "MySQL", "GCP", "Redis", "GitLab", "CI/CD"],
    },
    {
      company: "CODE RUNNERS",
      url: "https://www.code-runners.com/",
      icon: coderunner,
      iconMin: coderunner,
      location: "Sofia, Bulgaria",
      contract: "Full-time",
      position: "Web Developer",
      start: "Apr 2016",
      end: "Aug 2017",
      description: [
        "As a Full Stack Developer at Code Runners, a dynamic software development firm specializing in custom solutions for the advertising and marketing industries, my role spanned across both client-facing and technical domains, using an innovative tech stack predominantly featuring Django, React, Node, Bootstrap, and REST APIs. The position required a deep understanding of both frontend and backend development to create highly responsive and functional applications tailored to the unique needs of our diverse clientele.",
        "I took part in custom software solutions by architecting, coding, and maintaining complex web applications. My work included full ownership of projects from concept through deployment, emphasizing scalable and maintainable code.",
        "Utilizing **React**, I developed dynamic and interactive user interfaces that provided users with **real-time updates** on job listings, application statuses, and communications from potential employers. My focus was on creating a user-friendly experience that enhanced engagement and facilitated easier navigation through the platform. ",
        "I crafted numerous **RESTful APIs** that enabled the integration of various frontend and backend components. These APIs facilitated interactions such as user profile updates, job postings, application submissions, and employer feedback mechanisms.",
        "In the backend, I utilized **Django** to construct a comprehensive and efficient **ORM (Object-Relational Mapping)**, which significantly improved data retrieval and manipulation. I designed and implemented a database schema that supported complex queries for real-time job matching algorithms and user management. This also included setting up **Django** models and views to handle business logic and data processing effectively.",
        "Employed **Node.js** to implement **microservices** that handled specific tasks like **third-party service integrations** and **real-time data processing**, improving modularity and ease of maintenance of the platform. This was particularly effective in managing integrations with **LinkedIn** and **Google** for authentication and data scraping, streamlining these processes without impacting the core application logic managed by **Django**.",
        "The platform integrated several third-party services, including LinkedIn and Google for **authentication** and job **data scraping**. I managed these integrations to enrich the platform's capabilities, allowing users to import their profiles and job histories directly from LinkedIn, enhancing the application process and user profile completeness.",
        "I implemented best practices in **code optimization** and **responsive design** using **Bootstrap**, ensuring that the platform operated efficiently and was accessible on various devices. This involved optimizing query performances, reducing page load times, and ensuring that the platform's layout was responsive across desktops, tablets, and smartphones.",
        "Using **Git**, I maintained a well-documented and version-controlled codebase, which facilitated team collaboration. I implemented branching strategies and code review practices that ensured high-quality code and allowed for continuous integration and deployment without downtime.",
        "Given the sensitive nature of user data, I implemented stringent security measures, including **secure data transmission, encrypted storage**, and compliance with **GDPR** standards. Regular security audits were conducted to identify and mitigate potential vulnerabilities.",
        "I led the testing phase, which involved both automated and manual testing to ensure the application's reliability and performance. This included setting up a robust testing framework with **Django's** built-in features and **React testing utilities** to cover functional testing, unit testing, and user acceptance testing."
      ],
      skills: ["Django", "React", "Node", "Go", "Ruby", "Bootstrap", "REST APIs", "Git", "Javascript"],
    },
    {
      company: "DREAMIX",
      url: "https://dreamix.eu",
      icon: dreamix,
      iconMin: dreamix,
      location: "Sofia, Bulgaria",
      contract: "Full-time",
      position: "Web Developer",
      start: "Aug 2014",
      end: "Mar 2013",
      description: [
        "During my tenure at Dreamix, a reputed custom software development agency established in 2005, I played a pivotal role in the creation of a cutting-edge social media platform designed to cater to niche communities. With a dedicated team of 40 professionals, Dreamix specializes in developing tailored software, web, and mobile applications for small to midmarket businesses, leveraging technologies such as JavaScript, Kotlin, Swift, Python, HTML, CSS, and jQuery.",
        "I was actively involved in the initial planning phases, where we collaborated with stakeholders to define the project scope and objectives. This included conducting detailed requirement analysis sessions to ensure the platform met the specific needs of our target users and aligned with the client's business goals.",
        "Utilizing **Python** for **backend development**, I architected a robust and scalable **server-side solution** capable of handling high volumes of concurrent users and data transactions. The system architecture was designed to support extensive customization and easy integration with existing technologies.",
        "**I led the frontend development team**, focusing on crafting a responsive and visually appealing user interface. By employing modern **JavaScript frameworks** along with **HTML and CSS**, we ensured a seamless and engaging user experience. Our goal was to make the platform intuitive and accessible across various devices, including desktops and mobile phones.",
        "Implementing **jQuery**, we developed dynamic content features such as **real-time notifications, live chats, and user-generated content uploads**. These interactive elements were crucial in increasing user engagement and facilitating community interactions within the platform.",
        "I designed and implemented several **RESTful APIs** using **Python**, allowing for efficient communication between the frontend and backend. These APIs facilitated critical functionalities, including user authentication, content management, and social interactions, ensuring a smooth and secure user experience.",
        "To handle the **intensive workload** and ensure **data security**, I optimized the application for performance and scalability. This included refining database queries, implementing caching strategies, and conducting rigorous security assessments to protect user data and prevent potential cyber threats.",
        "I established a comprehensive testing protocol, overseeing a mix of automated and manual testing processes to ensure the platform's functionality and performance met our high standards. This rigorous QA process helped identify and fix issues prior to deployment, ensuring a bug-free launch.",
        "Following the successful testing phase, I managed the platform's deployment, which involved setting up cloud infrastructure and ensuring the environment was optimized for performance. Post-launch, I continued to lead the development team in iterative improvements, adding new features and making adjustments based on user feedback.",
      ],
      skills: ["Python", "JavaScript", "PHP", "HTML", "CSS", "jQuery", "Ajax"],
    },
  ],
  languages: [
    {
      name: "English",
      level: "C1",
    },
    {
      name: "Mandarin",
      level: "C2",
      native: "C2"
    },
  ],
  contact: {
    location: "Ankara, Turkey",
    email: "davydyang3@gmail.com",
    phone: "+90 212 3207438",
    website: "https://davyd.live/",
    linkedin: "https://www.linkedin.com/in/davyd-yang-5b3b02136/",
    github: "https://www.github.com/hereistopdev",
    researchgate: "davyd-yang",
    gitlab: "https://www.gitlab.com/hereistopdev",
    deviantart: "https://davyd.live/",
  },
  payment: {
    bitcoin: "",
    payoneer: "",
    paypal: "",
  },
};

export default details;
